# Generated by Django 4.2.24 on 2025-09-03 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storage', '0002_filecategory_academicsession_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicsession',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fileitem',
            name='original_filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
