# Generated by Django 4.2.7 on 2025-09-04 12:56

import django.core.validators
from django.db import migrations, models
import storage.models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_alter_academicsession_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileitem',
            name='file',
            field=models.FileField(max_length=500, upload_to=storage.models.upload_to_file, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'ppt', 'pptx', 'xls', 'xlsx', 'txt', 'zip', 'rar', 'jpg', 'jpeg', 'png', 'gif'])]),
        ),
    ]
