# Generated by Django 4.2.7 on 2025-09-04 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_alter_fileitem_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharelink',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='storage.folder'),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='file_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='storage.fileitem'),
        ),
    ]
