# Generated by Django 4.2.7 on 2025-09-04 14:08

from django.db import migrations, models
import storage.models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_sharelink_folder_alter_sharelink_file_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='File extension without dot, e.g., pdf, jpg, java', max_length=20, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='fileitem',
            name='file',
            field=models.FileField(max_length=500, upload_to=storage.models.upload_to_file, validators=[storage.models.validate_dynamic_extension]),
        ),
    ]
