# Generated by Django 4.2.7 on 2025-09-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_allowedextension_alter_fileitem_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicsession',
            name='allowed_faculties',
            field=models.ManyToManyField(blank=True, help_text='Faculties that can access this session', to='storage.department'),
        ),
        migrations.AddField(
            model_name='academicsession',
            name='is_faculty_specific',
            field=models.BooleanField(default=False, help_text='If True, this session is specific to certain faculties'),
        ),
    ]
