# Generated by Django 4.2.7 on 2025-09-04 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_academicsession_allowed_faculties_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='active_session',
            field=models.ForeignKey(blank=True, help_text='Active session for this department/faculty', null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.academicsession'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='active_session',
            field=models.ForeignKey(blank=True, help_text='Active session for this faculty (if faculty-specific)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.academicsession'),
        ),
    ]
