# Generated by Django 4.2.7 on 2025-09-04 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0008_department_active_session_userprofile_active_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicsession',
            name='allowed_faculties',
        ),
        migrations.RemoveField(
            model_name='academicsession',
            name='is_faculty_specific',
        ),
        migrations.RemoveField(
            model_name='department',
            name='active_session',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='active_session',
        ),
        migrations.AddField(
            model_name='department',
            name='active_session_override',
            field=models.ForeignKey(blank=True, help_text='Override active session for this faculty (leave blank to use global active session)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.academicsession'),
        ),
    ]
