# Generated by Django 4.2.7 on 2025-09-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0009_remove_academicsession_allowed_faculties_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicsession',
            name='name',
            field=models.CharField(help_text='e.g., 2024-25', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='academicsession',
            name='year',
            field=models.IntegerField(unique=True),
        ),
        migrations.AddConstraint(
            model_name='academicsession',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_session_name'),
        ),
        migrations.AddConstraint(
            model_name='academicsession',
            constraint=models.UniqueConstraint(fields=('year',), name='unique_session_year'),
        ),
    ]
