# Generated by Django 4.2.7 on 2025-09-04 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0010_alter_academicsession_name_and_more'),
    ]

    operations = [
    ]
