# Generated by Django 4.2.7 on 2025-09-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0012_logfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileitem',
            name='is_manual',
            field=models.BooleanField(default=False, help_text='True if file was manually added to media directory'),
        ),
    ]
