# Generated by Django 4.2.7 on 2025-09-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0013_add_is_manual_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='is_manual',
            field=models.BooleanField(default=False, help_text='True if folder was manually added to media directory'),
        ),
    ]
